server:
  port: 8080
spring:
  application:
    name: prometheus-test
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}