server:
  port: 8001
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smltq/spring-boot-demo.git
          searchPaths: cloud-config/config-repo
          force-pull: true